trigger:
  batch: 'true'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  condition: not(eq(variables['build.sourceBranch'], 'refs/heads/master'))
  jobs:
    - job: Build
      displayName: 'Build Solution'
      steps:
        - script: npx vsce package
          displayName: 'Package'
- stage: Publish
  condition: eq(variables['build.sourceBranch'], 'refs/heads/master')
  jobs:
    - job: Publish
      displayName: "Publish"
      steps:
        - script: npx vsce package
          displayName: 'Package'
        - script: npx vsce publish -p $(VS_MARKETPLACE_TOKEN)
          displayName: 'Publish'